//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analityc_Plan_Week
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analityc_Plan_Week()
        {
            this.Analityc_Plan = new HashSet<Analityc_Plan>();
        }
    
        public int Analityc_Plan_Week_id { get; set; }
        public string Analityc_Plan_Week_Nomenclature { get; set; }
        public string Analityc_Plan_Week_Date { get; set; }
        public string Analityc_Plan_Week_Volume { get; set; }
        public string Analityc_Plan_Week_Note { get; set; }
        public string Analityc_Plan_Week_Status { get; set; }

        public string Nomenclature_week
        {
            get
            {
                return "Номенклатура: " + this.Analityc_Plan_Week_Nomenclature;
            }
        }

        public string Date_week
        {
            get
            {
                return "Выполнить до: " + this.Analityc_Plan_Week_Date;
            }
        }

        public string Status_week
        {
            get
            {
                return "Статус выполнения: " + this.Analityc_Plan_Week_Status;
            }
        }

        public string Volume_week
        {
            get
            {
                return "Обьем: " + this.Analityc_Plan_Week_Volume;
            }
        }
        public string Note_week
        {
            get
            {
                return "Примечание: " + this.Analityc_Plan_Week_Note;
            }
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analityc_Plan> Analityc_Plan { get; set; }
    }
}
