//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analityc_Plan
    {
        public int Analityc_Plan_id { get; set; }
        public Nullable<int> Analityc_Plan_Day_id { get; set; }
        public Nullable<int> Analityc_Plan_Week_id { get; set; }
        public Nullable<int> Analityc_Plan_Month_id { get; set; }
    }
}
