//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analityc_Recipe
    {
        public int Analityc_Recipe_id { get; set; }
        public string Analityc_Recipe_Name { get; set; }
        public string Analityc_Recipe_Ingredients_One { get; set; }
        public string Analityc_Recipe_Ingredients_Two { get; set; }
        public string Analityc_Recipe_Ingredients_Three { get; set; }
        public string Analityc_Recipe_Ingredients_Four { get; set; }
    }
}
