//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analityc_Order
    {
        public int Analityc_Order_id { get; set; }
        public string Analityc_Order_Name { get; set; }
        public string Analityc_Order_Vendor_Code { get; set; }
        public string Analityc_Order_Weight { get; set; }
        public string Analityc_Order_Number_Boxes { get; set; }
        public string Analityc_Order_Date { get; set; }
        public string Analityc_Order_Status { get; set; }
    }
}
