//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analityc_Finished_Products
    {
        public int Analityc_Finished_Products_id { get; set; }
        public string Analityc_Finished_Products_Name { get; set; }
        public string Analityc_Finished_Products_Weight { get; set; }
        public string Analityc_Finished_Products_Number_Boxes { get; set; }
        public string Analityc_Finished_Products_Description { get; set; }
        public string Analityc_Finished_Products_Date { get; set; }
        public string Analityc_Finished_Products_Status { get; set; }
    }
}
