//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analityc_Stock
    {
        public int Analityc_Stock_id { get; set; }
        public string Analityc_Stock_Name { get; set; }
        public string Analityc_Stock_Feature { get; set; }
        public string Analityc_Stock_Weight { get; set; }
        public string Analityc_Stock_Description { get; set; }
        public string Analityc_Stock_Date { get; set; }
        public string Analityc_Stock_Status { get; set; }
    }
}
