//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analityc_Plan_Week
    {
        public int Analityc_Plan_Week_id { get; set; }
        public string Analityc_Plan_Week_Nomenclature { get; set; }
        public string Analityc_Plan_Week_Date { get; set; }
        public string Analityc_Plan_Week_Volume { get; set; }
        public string Analityc_Plan_Week_Note { get; set; }
        public string Analityc_Plan_Week_Status { get; set; }
    }
}
